#!/bin/bash -eux
#
# setup-bootloader - Install GRUB bootloader for Proxmox VE
#

export DEBIAN_FRONTEND=noninteractive

# Update package lists
apt-get update

# Install GRUB bootloader based on the system's boot mode
if [ -d /sys/firmware/efi ]; then
  # UEFI mode
  apt-get install -y grub-efi-amd64-signed shim-signed
else
  # BIOS mode
  apt-get install -y grub-pc
fi

# Install Proxmox VE kernel if not already installed
if ! dpkg -l | grep -qw 'pve-kernel'; then
  apt-get install -y pve-kernel-5.15
fi
